name: ci
on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        os: [ windows-2022, ubuntu-22.04 ]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - uses: ilammy/setup-nasm@v1

    - name: Generate Build Files & Build
      run: make all GENERATOR=Ninja BUILD_TYPE=Release NUM_JOBS=4

    - uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.os }}-build
        path: build/
        if-no-files-found: error
